// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY'] ?? '',
    appId: '1:861400423856:web:bfa36b2a9f1f261991afa7',
    messagingSenderId: '861400423856',
    projectId: 'sgzipbee',
    authDomain: 'sgzipbee.firebaseapp.com',
    storageBucket: 'sgzipbee.firebasestorage.app',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY'] ?? '',
    appId: '1:861400423856:android:cec1a61ae2b40bb7980a75',
    messagingSenderId: '861400423856',
    projectId: 'sgzipbee',
    storageBucket: 'sgzipbee.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? '',
    appId: '1:861400423856:ios:e0e7e09be238cc37980a75',
    messagingSenderId: '861400423856',
    projectId: 'sgzipbee',
    storageBucket: 'sgzipbee.firebasestorage.app',
    iosBundleId: 'sg.com.zipbee.customer',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? '',
    appId: '1:861400423856:ios:e0e7e09be238cc37980a75',
    messagingSenderId: '861400423856',
    projectId: 'sgzipbee',
    storageBucket: 'sgzipbee.firebasestorage.app',
    iosBundleId: 'sg.com.zipbee.customer',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY'] ?? '',
    appId: '1:861400423856:web:bfa36b2a9f1f261991afa7',
    messagingSenderId: '861400423856',
    projectId: 'sgzipbee',
    authDomain: 'sgzipbee.firebaseapp.com',
    storageBucket: 'sgzipbee.firebasestorage.app',
  );
}
